### ISSUE TITLE
New Documentation

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#102]
My idea is to have the main README point to other markdown files (for example backwards-compatibility notes) in the /docs/ folder.  I would create a subfolder /docs/JSdoc/ to store the current api.md and any further JSdoc files.  @Otto-AA and @bourgeoa - does this sound ok?

**Comment by Otto-AA** [comment]
Yes, sounds good. This is also similar to how it would be done with docsify, so in the future it should be easy to add this visualization.

If we make a docs folder, we can also use github pages to serve it. Then our examples could be tested there.

**Comment by jeff-zucker** [comment]
I think that I have completed the README for v.1.0.0 with two exceptions : 1) a detailed description of the error response (I've done a prelimnary one that should suffice for novice use with single-error messages) and 2) Otto's last name (if he wants it to be something other than AA in the acknowledgements).   I'm afraid that both of these depend on @Otto-AA since I am not sure I understand the error mechanism myself.  As far as I'm concerned we can launch without the detailed description of errors and other than review of the README and Otto's refactoring, we are ready to launch.  Anything I am forgetting?

**Comment by Otto-AA** [comment]
I haven't had time the last days, so I will take a look at it tomorrow and come back to you.

Regarding the name, I'd prefer not to use my real name. I'm fine with Otto-AA or just A_A, if possible as a link to the github repo.

**Comment by jeff-zucker** [comment]
Thanks, no pressure from my end, you've got a lot to do.

**Comment by Otto-AA** [comment]
From skimming over the README.md:
I guess that this won't work:
```javascript
    if( !fc.itemExists(x) ) {
        fc.createFolder(x) // only create if it doesn't already exist
    }
```
We need to wait for the promise to resolve, e.g. `if (!(await fc.itemExists(x))) await fc.createFolder(x)`

As far as I've seen now, the examples are spread over the documentation at the places where they belong to. Additionally I think it would be good to have a Examples section with links to examples of common use cases.

**Comment by bourgeoa** [comment]
- I commit a typo on L258
- Could you add the optional field `links` in readFolder() structure in brackets after the `url`
- linked files : is there a need to be more precise on the process of making the .acl relative including a change in `accessTo object` if needed.

@jeff-zucker You made a fairly accessible documentation.
You may add a fetch() with acceptHeader text/turtle

@Otto-AA Complex error reporting do not seem to be what I would have expected.
May be we should have a `new Response` prototype with : ok, status, message as global result for the complex method, and body containing body.success and body.errors for details.
example : 
- `response.ok=true` and `response.status=200` for `deleteFolder` on success
- `response.ok=false` and `response.status=309` for `deleteFolder` when the folder is not void, body containing more details in case of more than one error

**Comment by jeff-zucker** [comment]
> * I commit a typo on L258

Thanks.  For the time being could you not commit directly.  Please either just message me the typo for small things or create a PR.  

> * Could you add the optional field `links` in readFolder() structure in brackets after the `url`

It lists options and that is how all methods are listed.  The list of what the options are is in the Advanced Options section.  That is how all the methods are done and I believe it makes things less confusing.

> * linked files : is there a need to be more precise on the process of making the .acl relative including a change in `accessTo object` if needed.

I'm sorry, I do not understand your suggestion, could you explain.

> 
> @jeff-zucker You made a fairly accessible documentation.
> You may add a fetch() with acceptHeader text/turtle

Thanks, will do.

> @Otto-AA Complex error reporting do not seem to be what I would have expected.
> May be we should have a `new Response` prototype with : ok, status, message as global result for the complex method, and body containing body.success and body.errors for details.
> example :
> 
> * `response.ok=true` and `response.status=200` for `deleteFolder` on success
> * `response.ok=false` and `response.status=309` for `deleteFolder` when the folder is not void, body containing more details in case of more than one error

I agree that deleteFolder, copyFile, etc. should return ok=true/status=200 on success.  response.ok=false is kind of superfluous because it will never be found in the response object, only in the error object.

**Comment by jeff-zucker** [comment]
I just added in a number of code examples to the README, especially for the advanced options.  I also pointed to @Otto-AA's examples in the examples folder.

**Comment by Otto-AA** [comment]
> @Otto-AA Complex error reporting do not seem to be what I would have expected.
May be we should have a new Response prototype with : ok, status, message as global result for the complex method, and body containing body.success and body.errors for details.
example :
    response.ok=true and response.status=200 for deleteFolder on success
    response.ok=false and response.status=309 for deleteFolder when the folder is not void, body containing more details in case of more than one error

For the error reporting your suggestion is pretty much the same as the current implementation. It has following properties:
```javascript
    this.successful = successful // successful promises
    this.rejected = rejectedErrors.map(err => err.response) // rejected responses
    this.rejectedErrors = rejectedErrors // rejected responses wrapped inside error (can access msg; internal usage; maybe not many use cases for the outside)
    this.errors = errors // non-fetch errors (e.g. invalid arguments)
    this.ok = false
```
What probably differs from your suggestion is, that the fetch errors and other errors are separated.

For a successful `deleteFolder`, what would be the use case of giving it a `response.ok` and `response.status`? If it is successful, these values are implicitly known and I currently don't see why I would check for these.

**Comment by bourgeoa** [comment]
> * linked files : is there a need to be more precise on the process of making the .acl relative including a change in `accessTo object` if needed.

When you copyFile(from, to) withAcl=true from.acl contains accessTo ./from name which is replaced by ./to name.
You are relative to parent and to destinationName.
May be it implicit.

**Comment by jeff-zucker** [comment]
> For a successful `deleteFolder`, what would be the use case of giving it a `response.ok` and `response.status`? If it is successful, these values are implicitly known and I currently don't see why I would check for these.

Hmm,  that makes sense.  What about for post() - that returns a response object, right?  How else could we find the location of the created resource, otherwise.

**Comment by jeff-zucker** [comment]
> > * linked files : is there a need to be more precise on the process of making the .acl relative including a change in `accessTo object` if needed.
> 
> When you copyFile(from, to) withAcl=true from.acl contains accessTo ./from name which is replaced by ./to name.
> You are relative to parent and to destinationName.
> May be it implicit.

I expalin that and the noModify flag in the section on Linked Resources.  Is that not sufficient?

**Comment by bourgeoa** [comment]
> For a successful `deleteFolder`, what would be the use case of giving it a `response.ok` and `response.status`? If it is successful, these values are implicitly known and I currently don't see why I would check for these.

How do I know that deleteFolder was a success.
Actually it returns an array of 200'th

**Comment by bourgeoa** [comment]
> I expalin that and the noModify flag in the section on Linked Resources. Is that not sufficient?

May be it is I was just wondering ?

**Comment by Otto-AA** [comment]
> Hmm, that makes sense. What about for post() - that returns a response object, right? How else could we find the location of the created resource, otherwise.

post returns only a single response. Recursive methods return an array of responses.

> How do I know that deleteFolder was a success.
Actually it returns an array of 200'th

It will throw if an error occurs. If it doesn't throw, then it succeeded : (not tested, but the principle should work at least)
```javascript
fc.deleteFolder(url)
  .then(() => console.log('Succeeded'))
  .catch(err => console.error(`Error: ${err}`))
// Or with async-await
try {
  const responses = await fc.deleteFolder(url)
  console.log('Succeeded')
} catch (err) {
  console.error(`Error: ${err}`)
}
```

**Comment by jeff-zucker** [comment]
@Otto-AA - do I understand recursive methods correctly - if all operations succeed the method succeeds, if some of the operations fail, it does not throw immediately, but performs the operations it can and then fails.

**Comment by Otto-AA** [comment]
>  Actually it returns an array of 200'th

This could be used to log what items have been deleted, e.g. like this:
```javascript
try {
  const responses = await fc.deleteFolder(url)
  console.log('Succeeded')
  responses.forEach(res => console.log(`Deleted: ${res.url}`))
} catch (err) {
  console.error(`Error: ${err}`)
}
```

**Comment by Otto-AA** [comment]
> @Otto-AA - do I understand recursive methods correctly - if all operations succeed the method succeeds, if some of the operations fail, it does not throw immediately, but performs the operations it can and then fails.

Yes. And with the error thrown one can check what succeeded and what caused the error.

**Comment by bourgeoa** [comment]
@jeff-zucker 
for the examples : is there a way to copy from a https:// pod to file://, and reverse.

**Comment by jeff-zucker** [comment]
> @jeff-zucker
> for the examples : is there a way to copy from a https:// pod to file://, and reverse.

See https://github.com/jeff-zucker/solid-file-client/blob/otto-changes/docs/node-upload.js

**Comment by bourgeoa** [comment]
Thanks I shall look at it

Le jeu. 19 déc. 2019 à 21:28, Jeff Zucker <notifications@github.com> a
écrit :

**Comment by jeff-zucker** [comment]
I just added  file:// <--> https:// examples in the introduction.

**Comment by bourgeoa** [comment]
@jeff-zucker 
I just had a look to the README.md and I have a few comment : 
- still TBD error response
- in advanced-options
 -- `withAcl true/false` could be added
 -- in` linked-files` 
    . at the end of readFolder(). I would add : `a links field is added to the folder object (and respectively subfolders/files)`
    . getPossibleLinks is to be replaced by `getItemLinks(url, options)` and I will add an example link parameter
-- the advanced options are not commented using the solid-file-client constants

**Comment by jeff-zucker** [comment]
> * in advanced-options
>   -- `withAcl true/false` could be added

I thought we agreed on a single option links=include/exclude/includePossible.  

>   -- in` linked-files`
>   . at the end of readFolder(). I would add : `a links field is added to the folder object (and respectively subfolders/files)`

Yes, I should explain how the links are returned and give an example of accessing them.

>   . getPossibleLinks is to be replaced by `getItemLinks(url, options)` and I will add an example link parameter

Yes, thanks for the reminder.

>   -- the advanced options are not commented using the solid-file-client constants

Sorry, I'm not sure what you mean.

**Comment by Otto-AA** [comment]
> I thought we agreed on a single option links=include/exclude/includePossible.

I don't remember what we agreed on. Currently it's implemented like this:
- readFolder (url, { links: LINKS.EXCLUDE/... })
- copyFolder (from, to, { withAcl: true, withMeta: true })

I'd be opposed to using `links: include/exclude` in copyFolder as copying acl and meta files are completely different use cases imo.

**Comment by Otto-AA** [comment]
>     -- the advanced options are not commented using the solid-file-client constants
> Sorry, I'm not sure what you mean.

I guess this is meant:
```javascript
await copyFolder( source, target, {merge:"source"} )
```
I think the preferred way should be:
```javascript
const { MERGE, LINKS } = SolidFileClient
await copyFolder( source, target, {merge: MERGE.KEEP_SOURCE } )
// or
const { MERGE: { KEEP_SOURCE }, LINKS } = SolidFileClient
await copyFolder( source, target, {merge: KEEP_SOURCE } )
```

The last version would be (nearly) typo-proof. And theoretically we could change the values of the constants and users wouldn't need to change their code. Imo the main use for the value of the constants is that it can be logged to the console. Apart from that I would always use constants and also document it that way.

**Comment by jeff-zucker** [comment]
Version 1.0.0. is now released, closing  background issues.
