### ISSUE TITLE
Maintaining the 0.x solid file client

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#105]
While I do not think we should be maintaining the old version, I do think we should leave it online for at least a transition period.  As long as it is online, we should make sure that it does not have security vulnerabilities i.e. passes npm audit.  I believe I've fixed all the current ones, will commit soon.

@bourgeoa in the old version we have both package-lock.json and yarn.lock - we should only have one AFAIK.  Should I just remove the yarn stuff?

**Comment by bourgeoa** [comment]
Sorry I have absolutely no idea, not learned what it means.

**Comment by Otto-AA** [comment]
> While I do not think we should be maintaining the old version, I do think we should leave it online for at least a transition period.

What do you mean with leaving it online? As a second branch on github?

> As long as it is online, we should make sure that it does not have security vulnerabilities i.e. passes npm audit. I believe I've fixed all the current ones, will commit soon.

I just want to note, that I don't think that fixes to the old version after publishing v1.0.0 will make it to npm. Hence if someone wants those they would need to download it from the second branch directly.

**Comment by jeff-zucker** [comment]
>
> What do you mean with leaving it online? As a second branch on github?
>

Yes a separate branch and an npm version.

> I just want to note, that I don't think that fixes to the old version
> after publishing v1.0.0 will make it to npm. Hence if someone wants those
> they would need to download it from the second branch directly.
>
>
I'm pretty sure that one can keep adding to a 0.x line while a 1.x line
exists. And if a person's package.json defines a dependency on 0.x they get
the latest in the 0 line even if the 1 line exists.   But I'll need to
check on that.  Let's not worry about it for now.  I'll npm one last
version 0.5.3 and if/when it needs updating I'll worry about it.

>

**Comment by jeff-zucker** [comment]
Version 1.0.0. is now released, closing  background issues.
