### ISSUE TITLE
updateFile try to delete file without extension when used with contentType

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#12]
When updateFile is used with third parameter content type and without file extension then you got always 404 error because delete looks for the file without extension.

**Comment by jeff-zucker** [comment]
Hopefully fixing the other issue about the 404 on update will fix this too.

**Comment by jeff-zucker** [comment]
I'm pretty sure that now that deleteFile() doesn't thow  an error on 404, this problem has gone away.  If I say updateFile("...foo","new content","text/turtle") it creates ...foo.ttl with no error from an attempted remove. Does this solve what you're asking about?

**Comment by bourgeoa** [comment]
I suppose
