### ISSUE TITLE
check if links meta and acl not undefined

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#125]
Headers my not contains .meta or .acl and return indefined. (this is the case for index.html at podRoot with NSS 5.2.2)
Shall we just pass silently, throw error or return information (there is no function that)

**Comment by Otto-AA** [comment]
If metaFrom exists, but metaTo is undefined, we should definitely throw imo.

If metaFrom is undefined, I'm not sure. I feel that the spec ([here](https://github.com/solid/solid-spec/blob/master/content-representation.md#metadata)) does not clearly states if the link header has to be present for all items. So we shouldn't rely on them being present.
This is why I'd tend to return undefined if metaFrom is undefined, and not to throw an Error in that case.

**Comment by bourgeoa** [comment]
For files we should not look at meta in header that is the purpose of my PR.
For folders it is a MUST it should always exist
So if we include the above PR, whenever meta or acl is undefined we should throw error.
The workflow is such that the 'to' file or folder is created.

**Comment by Otto-AA** [comment]
> For files we should not look at meta in header that is the purpose of my PR.

There are also files which can have meta files (everything which is not RDF, e.g. pictures and music). Imo we should always check if the meta file exists, also for files, and then copy it (when the option is true).

**Comment by bourgeoa** [comment]
Not in NSS actually, in future spec may be.
It is difficult to pre-empt on future spec.

We can also just `return` when `possible-link` is `undefined` without throwing any error

**Comment by Otto-AA** [comment]
> Not in NSS actually, in future spec may be.
It is difficult to pre-empt on future spec.

It is part of the current spec that non-rdf resources can have meta files (from [here](https://github.com/solid/solid-spec/blob/master/content-representation.md#metadata)):
> The metadata (extra RDF triples such as types, titles, comments, and so on) about non-RDF resources (e.g. containers, images, binaries, etc.) will be stored in a corresponding meta resource.

> We can also just return when possible-link is undefined without throwing any error

This is also what I would propose. If `metaFrom` is undefined, then we should return undefined imo.
If it is defined, but `metaTo` is not we should probably throw imo.
If both are defined, we should try to copy it. Currently it fails with 404 if it doesn't exist.

**Comment by jeff-zucker** [comment]
My opinion : From the user's perspective, reading, copying, and moving
should succeed if it is possible to read/copy/move the requested item.  If,
for whatever reason, it isn't possible to find out about or to
read/copy/move associated .meta or .acl resources, we should log a warning
so the user knows that happened but we should not fail.  So I don't really
care whether looking for .meta returns undefined or throws, I care that our
code traps either event and does what the user expects.

> If both are defined, we should try to copy it. Currently it fails with
404 if it doesn't exist.

I don't understand this. Why should it fail if it can't find a file which
is completely optional and more likely not to be there than it is to be
there?

Separate from the issue of whether links can be found in the header (which
AFAIK only relates to a single NSS bug on the pod root's index.html), is
the fact that NSS does not implement .meta for resources, only for
containers.  This means that all of the effort of finding .meta files for
resources is wasted and that not finding .meta for files is 100%
guaranteed. Presumably IPS will implement .meta for files.  So I guess we
should keep looking for .meta even though we know it is not there currently
because in the future it may be there.  But we should definitely not fail
on not finding it, because currently that will always happen.

**Comment by jeff-zucker** [comment]
From [the current spec](https://github.com/solid/solid-spec/blob/master/content-representation.md):

"Servers must support the HEAD method for reading data. This returns a list of headers related to the resource in question. Among these headers, two very important Link headers contain pointers to corresponding ACL and metadata resources"

Note the use of MUST.  While it doesn't specifically say that .meta and .acl MUST be included, it strongly implies that.

**Comment by bourgeoa** [comment]
I propose to add in SolidApi.js : 
- L499
```
    if (aclFrom === undefined) return
    if (aclTo === undefined) return console.log('404 - acl link undefined ' + newTargetFile)

```
- and L475
```
    if (metaFrom === undefined) return
    if (metaTo === undefined) return console.log('404 - meta link undefined ' + newTargetFile)

```

It may be a bug, but it solves the problem for now and do not harm the future
We may add it's a hack for NSS.
@jeff-zucker you surely have a better coding with `new Error()`

**Comment by Otto-AA** [comment]
> I don't understand this. Why should it fail if it can't find a file which
is completely optional and more likely not to be there than it is to be
there?

It only fails with 404 if the user explicitly says to copy the meta file when directly calling `copyMetaFileForItem`. If the user calls `copyLinksForItem` it will copy only the existing links without throwing 404 if one doesn't exist. Latter is also used in copyFile and copyFolder.

> My opinion : From the user's perspective, reading, copying, and moving
should succeed if it is possible to read/copy/move the requested item.  If,
for whatever reason, it isn't possible to find out about or to
read/copy/move associated .meta or .acl resources, we should log a warning
so the user knows that happened but we should not fail.

If the copy request should also copy the meta files (ie `withMeta` is true), a meta file exists but the copying of it fails, I think the copy request should fail too. Not failing silently or logging it somewhere.

So for example when calling `copyFile(from, to, { withMeta: true })` I would imagine something like this:
```
read metaFrom location
if (metaFrom location is undefined)
  return undefined
if (metaFrom exists) {
  read metaTo location
  if (metaTo is undefined) throw
  res = copyFile(metaFrom, metaTo)
  if (res failed) throw
  else return res
}
```

Regarding logging, I am opposed to use it if it's not enabled. When the user enabled it we can use it to log warnings about undefined meta locations (or whatever else). If it's not enabled I would not use it. But we could set the default logging to true (or true for specific logging cases)

**Comment by jeff-zucker** [comment]
On Wed, Jan 8, 2020 at 3:28 PM A_A <notifications@github.com> wrote:

> It only fails with 404 if the user explicitly says to copy the meta file
> when directly calling copyMetaFileForItem. If the user calls
> copyLinksForItem it will copy only the existing links without throwing
> 404 if one doesn't exist. Latter is also used in copyFile and copyFolder.
>

Okay, that makes sense.  I would recommend that we use 500 if the failure
to copy is that the server didn't provide the link header info - that is a
server error, not a file-not-found.

> If the copy request should also copy the meta files (ie withMeta is
> true), a meta file exists but the copying of it fails, I think the copy
> request should fail too. Not failing silently or logging it somewhere.
>
I agree that if we have a metaFrom and a metaTo  or aclFrom and aclTo and
we try to copy and that fails, it should be an error.  I do not agree that
should happen in the case where there is no metaTo or aclTo - that is not a
failure of copying, it is a bug in NSS.  I would prefer that we not throw
an error in that case.  Remember that this bug impacts the pod's index.html
and having that invariably fail would not be a service to our users.

 Regarding logging, I am opposed to use it if it's not enabled. When the
> user enabled it we can use it to log warnings about undefined meta
> locations (or whatever else). If it's not enabled I would not use it. But
> we could set the default logging to true (or true for specific logging
> cases)
>
It's fine with me if it only gets logged if logging is enabled.

**Comment by jeff-zucker** [comment]
Tangentially related to this issue - why do forbid users from copying a .acl or .meta file directly?  I  can think of many use cases where I'd create an .acl for one folder and want the same rights for a series of other folders and would want to copy it to the .acl but not necessarily other folder contents.

**Comment by Otto-AA** [comment]
> I agree that if we have a metaFrom and a metaTo  or aclFrom and aclTo and
we try to copy and that fails, it should be an error.  I do not agree that
should happen in the case where there is no metaTo or aclTo - that is not a
failure of copying, it is a bug in NSS.  I would prefer that we not throw
an error in that case.  Remember that this bug impacts the pod's index.html
and having that invariably fail would not be a service to our users.

I think your description matches my suggestions above, I don't see any differences between it and the pseudo-code I've written above.

> Okay, that makes sense.  I would recommend that we use 500 if the failure
to copy is that the server didn't provide the link header info - that is a
server error, not a file-not-found.

Ok, I'll summarize what I'd like for the `copyMetaFileForItem` and `copyLinksForItem` methods:
copyMetaFileForItem:
```
metaFrom undefined -> return undefined (user can check if it's a response or undefined if he wants to know if it's been copied or not)
metaFrom defined & metaTo undefined -> throw error
metaFrom defined & metaTo defined -> try copy
error while copying -> throw error (e.g. 404, 401, ...)
```
copyLinksForItem
```
if (withMeta) {
  copyMetaFileForItem(...)
    .catch(404) // ie ignore when metaFrom was defined, but it didn't exist
}
if (withAcl) {
  copyAclFileForItem(...)
    .catch(404) // ie ignore when aclFrom was defined, but it didn't exist
}
```
Is it clear what I mean with this?

**Comment by Otto-AA** [comment]
> Tangentially related to this issue - why do we forbid users from copying a .acl or .meta file directly? I can think of many use cases where I'd create an .acl for one folder and want the same rights for a series of other folders and would want to copy the .acl but not necessarily other folder contents.

They can do it using `copyAclFileForItem(item1, item2, options)`. It would be simple to refactor it so we have `copyAclFileForItem(item1, item2, options)` and also `copyAclFile(acl1, acl2, options)` if you mean that.

**Comment by jeff-zucker** [comment]
On Thu, Jan 9, 2020 at 12:59 AM A_A <notifications@github.com> wrote:

> I agree that if we have a metaFrom and a metaTo or aclFrom and aclTo and
> we try to copy and that fails, it should be an error. I do not agree that
> should happen in the case where there is no metaTo or aclTo - that is not a
> failure of copying, it is a bug in NSS. I would prefer that we not throw
> an error in that case. Remember that this bug impacts the pod's index.html
> and having that invariably fail would not be a service to our users.
>
> I think your description matches my suggestions above,
>
Mostly, but not entirely :

> metaFrom defined & metaTo undefined -> throw error

As I said, I do not believe there should be an error when one or both
of metaFrom and metaTo are undefined (and same for acl).  We *know*
that this will always error with NSS when copying to the pod root
index.html.  If the bug ever gets fixed or a new server is announced,
we can make this throw, but for now it will confuse a lot of people.
It has already happened with Angelo Veltens.



> Okay, that makes sense. I would recommend that we use 500 if the failure
> to copy is that the server didn't provide the link header info - that is a
> server error, not a file-not-found.
>
> metaFrom defined & metaTo undefined -> throw error
>

From my point of view, this should not (currently) throw an error.  If
eventually it does, it should be 500.  Otherwise, I agree with your
pseudocode.

**Comment by Otto-AA** [comment]
We could also change it from 
```metaFrom defined & metaTo undefined -> throw error```
to
```metaFrom defined & metaTo undefined & itemExists(metaFrom) -> throw error```

I think we should throw an error in that case, because some information doesn't get copied. If we'd want to copy a html file + it's meta file to the pod root and it only is able to copy the html file it should fail imo. If we only copy a html file without a meta file it would succeed this way.

**Comment by jeff-zucker** [comment]
On Thu, Jan 9, 2020 at 9:38 AM A_A <notifications@github.com> wrote:

> We could also change it from
> metaFrom defined & metaTo undefined -> throw error
> to
> metaFrom defined & metaTo undefined & itemExists(metaFrom) -> throw error
>
> I think we should throw an error in that case, because some information
> doesn't get copied. If we'd want to copy a html file + it's meta file to
> the pod root and it only is able to copy the html file it should fail imo.
> If we only copy a html file without a meta file it would succeed this way.
>

So in other words, it is not possible to use our package to copy an
index.html to a pod root if there is an index.html.acl?  Why are we passing
on this NSS bug to users when we could easily protect them from it?


>
>

**Comment by jeff-zucker** [comment]
Something I just thought about - it is possible that NSS does not want us
to be able to replace the index.html, in which case failing is what we
should do. I'll raise an issue.

**Comment by Otto-AA** [comment]
> So in other words, it is not possible to use our package to copy an
index.html to a pod root if there is an index.html.acl?  Why are we passing
on this NSS bug to users when we could easily protect them from it?

If we do it like I suggested it will be possible to copy an index.html file to the pod root. Two scenarios so it hopefully gets more clear:

```javascript
/* Folder structure:
/foo/index.html
/bar/index.html
/bar/index.html.acl */

copy('/foo/index.html', '/index.html', { withAcl: true }) // will work
copy('/bar/index.html', '/index.html', { withAcl: true }) // will fail
copy('/bar/index.html', '/index.html', { withAcl: false }) // will work
```

It will only fail if the user tries to copy an acl/meta file to index.html which we probably aren't able to do right now. I didn't take a look at the cause of the issue though, but if the error is that the links are undefined for the root html, then my suggestion should make the results above.

> Something I just thought about - it is possible that NSS does not want us
to be able to replace the index.html, in which case failing is what we
should do. I'll raise an issue.

I've read several times in the forum that we can replace the index.html file, I've never read that we shouldn't do that.

**Comment by jeff-zucker** [comment]
Well that still leaves the default copy failing in the one case.  But I'm willing to live with that, let's just do it the way you suggest.

**Comment by Otto-AA** [comment]
It would only fail if someone tries to copy a index.html file to the root which has an acl file. If it hasn't got an acl file it would also work with the default copy. If it has one, one could modify the options accordingly.

**Comment by Otto-AA** [comment]
If you want, I can quickly implement it, but I likely won't be able to try it out and test it. Or you just implement it yourself.

**Comment by jeff-zucker** [comment]
That would be great if you can implement and I'll test and repair if needed.  Then again, if you don't have time, I think I can implement.

**Comment by Otto-AA** [comment]
Here's the prototype: https://github.com/Otto-AA/solid-file-client/tree/copy-links-prototype
The automated tests pass, so it shouldn't break anything. But you still need to test if it does what we concluded here. You can just copy-paste SolidApi.js or also clone the branch if you want.

**Comment by jeff-zucker** [comment]
Thanks!  I'll cut and paste and test it.

**Comment by jeff-zucker** [comment]
Unfortunately this fails even without any links in the source.  I get the error
```
Error: -1 SFCFetchError Cannot read property 'endsWith' of undefined
```

**Comment by Otto-AA** [comment]
Ahh, I forgot one case. Try replacing the method with this:
```javascript
  async _linkUrlsDefined(from, to) {
    if (typeof from === 'string' && typeof to !== 'string' && await this.itemExists(from)) {
      throw toFetchError(new Error('Cannot copy link file because target location was not provided by the pod'))
    }
    return (typeof from === 'string' && typeof to === 'string')
  }
```

**Comment by jeff-zucker** [comment]
Yep,  I discovered that just now too.  My change is:
```
 async _linkUrlsDefined(from, to) {
    if (typeof from !== 'string') {
      return false
    }
    else if ( typeof to !== 'string' && await this.itemExists(from)) {
      throw toFetchError(new Error('Cannot copy link file because target locati\
on was not provided by the pod'))
    }
    else if ( typeof(to) !== 'string' ) {
      return false
    }
    else {
      return true
    }
  }

```

**Comment by jeff-zucker** [comment]
It looks like everything now works the way we decided as v1.0.2.  THANKS.
