### ISSUE TITLE
createFile README.md do not list parameters

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#13]
createFile uses the same parameters than updateFile which does not seem to be the case reading the README.me

**Comment by jeff-zucker** [comment]
Good point, thanks for catching it.  Fix on the way.

**Comment by jeff-zucker** [comment]
Fixed, as well as @scenaristeur's excellent patch to return the name of the file actually created.  Both in the new README, uploading soon.
