### ISSUE TITLE
CopyFile works on folders!

### ISSUE THREAD

**Issue by CxRes** [jeff-zucker/solid-file-client#132]
The following work on folders without problems: 
```js
fc.copyFile('https://example.inrupt.net/public/data', 'https://example.inrupt.net/public/data2
fc.copyFile('https://example.inrupt.net/public/data/', 'https://example.inrupt.net/public/data2
```

And this throws with status 409
```js
fc.copyFile('https://example.inrupt.net/public/data', 'https://example.inrupt.net/public/data2/
fc.copyFile('https://example.inrupt.net/public/data/', 'https://example.inrupt.net/public/data2/
```
with message (data2 does not exist):
```
SFCFetchError 409 https://example.inrupt.net/public/data2/ - A conflict appeared. If you tried to delete a folder, make sure that it is empty.
```

Meanwhile copyFolder has its own quirks. See next issue...

**Comment by bourgeoa** [comment]
When it works it does create a folder and do not copy contents.
I suppose it should not work on folders.

@jeff-zucker I can make a PR if you are OK (checking `from/to` do not end with` /`)

**Comment by jeff-zucker** [comment]
I believe it is correct to throw an error in these cases, but it should be clearer than "conflict".  In other words,  @CxRes's examples that didn't work should throw the errors "Files may not be copied onto folders!" and "Folders may not be copied onto files."

**Comment by CxRes** [comment]
@bourgeoa In my case, copyFile seems to copy files within the folder. The folder inside it is copied as a file and you get a 404 when trying to access it. I'll post a file with outputs here (once I can perform all the interesting tests) and you cross-check with my pod.

@jeff-zucker Incidentally, is there a reason why the general `copy` and `move` are not documented in the readme?

**Comment by CxRes** [comment]
Here are the [results](https://github.com/jeff-zucker/solid-file-client/files/4331950/sfc.txt). You can see the slash issues with folders a bit problematic even in copyFolder. Its actually a .md file (which github refuses to upload). You can cross-check each case with my pod. 

Incidentally, there seems to be no `moveFile` and `moveFolder` as documented in the readme?

**Comment by CxRes** [comment]
One last query: Would it not be sensible to have single `copy` method that determines the `type` from the GET request and use that information to proceed?

**Comment by bourgeoa** [comment]
solved with PR #134

**Comment by bourgeoa** [comment]
> One last query: Would it not be sensible to have single copy method that determines the type from the GET request and use that information to proceed?

It does exist and is not documented on README but is documented in [API doc](https://github.com/jeff-zucker/solid-file-client/blob/master/docs/JSdoc/api.md)

```
L615-622 from solidApi.js

  copy (from, to, options) {
    // TBD: Rewrite to detect folders not by url (ie remove areFolders)
    if (areFolders(from, to)) {
      return this.copyFolder(from, to, options)
    }
    if (areFiles(from, to)) {
      return this.copyFile(from, to, options)
    }

```

**Comment by CxRes** [comment]
@bourgeoa I saw that later but I was thinking of something that is tighter (that make copyFile and copyFolder irrelevant to userland). One may not know what kind of resource they have beforehand and the present will burden that user to place an unnecessary server call to check if it is a resource or a container - a call that the code makes anyway because it has to fetch the resource. While temporarily ok, I do not like the relevant slash for  GET requests.

**Comment by CxRes** [comment]
@jeff-zucker @bourgeoa Please look at #136

**Comment by bourgeoa** [comment]
> One may not know what kind of resource they have beforehand and the present will burden that user to place an unnecessary server call to check if it is a resource or a container

Theoretically may be, but I do not really see a use case. I personaly think the user must know if he is working with `container or resource` (folder or file) when using the `solid file client`.

[solid-ide](https://github.com/jeff-zucker/solid-ide) uses the copy function

As defined by SOLID on the client side a URI with a '/' is a container and it is a MUST. This is confirmed in the on-going specifications.

I think it is good for the user to be aware of that upfront.

**Comment by cerebrowang** [comment]
niubility

**Comment by CxRes** [comment]
@bourgeoa The issue is especially relevant when the URI is provided out of band (The first time you open a browser, bookmarks aside, you actually type in an address). For those cases the burden is on the user to first check whether they have a resource or a container which leads to definite extra call. Even for in band cases, it can represent an extra, though not unreasonable, programming burden. So I am gonna have to politely disagree with you on this one.

> As defined by SOLID on the client side a URI with a '/' is a container and it is a MUST. This is confirmed in the on-going specifications. 

Sure, URI with a '/' is a container according to spec, it does not say that URI without the '/' is definitely interpreted as a resource and not a container (perhaps it should be). Look at, for example, NSS, the canonical implementation of the spec. It actually allows for a http fetch to happen on a container irrespective of the trailing slash. To buttress this point with the example of your local file system, your file browser will also allow you to leave out a trailing slash (It will happily navigate irrespective of what address you put in the address bar, provided it exists). 

With #136, I demonstrate that even without this knowledge you can achieve a universal copy (I have also written implementations for move and delete which I shall PR based on feedback of copy, once @jeff-zucker gets better!) with no extra work, since you read the resource anyway. IMHO asking users to track information already available is contrary to the purpose of a high level library, which is looking to ease user burden (take a look at something like fs-extra for reference)

Lastly, I am also not asking for removal of the other resource specific copy and move functions, so you can continue to happily use them if you so prefer. In any case, as a rule, you should never break user land!
