### ISSUE TITLE
createFile does not exist anymore in bundle ?

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/solid-file-client#135]
Hi jeff, I've just npm installed solid-file-client, and used the /window/...bundled.min.js, but it seems that there is no more fileclient.createFile function  ??? Has it been removed ? 
Thxs

**Comment by jeff-zucker** [comment]
This prints "ok" for me:
```javascript
const auth       = require('solid-auth-cli')
const FileClient = require('solid-file-client')
const fc         = new FileClient(auth)

async function main(){
  let file     = "file://" + process.cwd() + "test.txt"
  let expected = "some text"
  let response = await fc.createFile( file, expected, "text/plain" )
  let got = await fc.readFile( file)
  console.log( got===expected && response.status==201 ? "ok" : "fail" )
}
main()
```

**Comment by scenaristeur** [comment]
It's not on the server side but in the browser so I can't use const FileClient = require('solid-file-client') , I use this.fileClient = SolidFileClient; and it seems to be found as it can be displayed in the console.

For this project https://github.com/scenaristeur/salut , at this submit step https://github.com/scenaristeur/salut/blob/af78a77e2917391b42659ebc549253f143015c9f/src/post-element.js#L252 (Post menu at the bottom, then add a media)

When I use solid-file-client@1.0.2 dist\window\solid-file-client.bundle.js that i copy to my /dist/vendor/solid-file-client (with the .map)  I got this error 

![image](https://user-images.githubusercontent.com/4020744/76703807-ad9bf300-66d4-11ea-8135-02a44128418e.png)

and there is no createFile function as you can see in this bundle

but when i copy solid-file-client@0.5.2 dist\browser to my /dist/vendor/
solid-file-client from an more ancient project
It works as expected and there is a createFile function

![image](https://user-images.githubusercontent.com/4020744/76703961-0029df00-66d6-11ea-82b2-c36c4f0c1d38.png)

![image](https://user-images.githubusercontent.com/4020744/76703980-23548e80-66d6-11ea-919e-54ef414f8573.png)

Am I doing something wrong ?

**Comment by jeff-zucker** [comment]
You do not appear to be initializing solid-file-client correctly.  This changed in the transition to 1.x.  You need to get the FileClient object using require and then instantiate a new instance of that object.  Your code should use the instance, not the object.  See the instructions at https://github.com/jeff-zucker/solid-file-client/blob/master/docs/transition-to-v.1.md and let me know if you have any questions.

**Comment by jeff-zucker** [comment]
Or in the browser you just import with a script tag and SolidFileClient the object exists without require and then create an instance of it.

**Comment by jeff-zucker** [comment]
And BTW, the code I posted above is not for a server, it is for my local file system.

**Comment by scenaristeur** [comment]
yes you're right, not server but node local ;-) .
Ok it works now ! You are the King 

```
Response { type: "cors", url: "https://spoggy.solid.community/public/spoggy/Document/Gilloux.jpg", redirected: false, status: 201, ok: true, statusText: "Created", headers: Headers, body: ReadableStream, bodyUsed: false }
```

thxs
