### ISSUE TITLE
Mishandling of PUT slug

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#139]
@Otto-AA   can you explain why putFile has a slug?  I do not see a slug on PUT listed anywhere in the specs.  This is now causing issues with an update on NSS to 5.2.4.  If there's a reason this is in there, please let me know.
```
   const requestOptions = {
      headers: {
        link: LINK.RESOURCE,
        slug: getItemName(url),
        'Content-Type': contentType
      },
      body: content
    }
```

**Comment by Otto-AA** [comment]
No, I think you can safely remove it for `putFile`. I guess I thought, that if the server doesn't need it, it just ignores it, so I left it when copy-pasting (but that's no reason to leave it here)

**Comment by jeff-zucker** [comment]
I've remove slug from putFile in v.1.0.3.
