### ISSUE TITLE
add zip/unzip functions

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#140]
@Otto-AA @jeff-zucker
 
We have implemented zip/unzip in solid-ide and solid-file-management.
Do you think it could be directly implemented in solid-file-client ?

-- It is a complex high level function.
-- It is easy to import/export a file.zip but complex to export a folder
-- it is a way to implement some validity control on createFile() if file is an .acl

**Comment by jeff-zucker** [comment]
I think it would be a great idea.  I myself don't have time to devote to that now but I'd be glad to cheer from from the sidelines. :-)

**Comment by cerebrowang** [comment]
do you think its a good idea that add some a blockchain algorithm NOT
mining?

**Comment by bourgeoa** [comment]
@jeff-zucker @Otto-AA see PR #154 that includes zip/unzip and acl validation PR #153 
There are comments in each PR

Zip/unzip functions have been implemented in SolidFileClient.js : 

To make the code cleaner, is it possible to create a Zip class extension from SolidApi, export the class, and import the result in index.js ?

Thanks for all your comments.

**Comment by bourgeoa** [comment]
PR #162
