### ISSUE TITLE
UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Missing scope parameter in authentication request

### ISSUE THREAD

**Issue by Leoudayan** [jeff-zucker/solid-file-client#146]
Hi,
I tried to use solid file client today and I got the following error. But I used it 6 months ago and when i run that old code now, it works. But When i set it up in a different machine, it is now working :( Following is the error. 
```

[ERROR]  (node:14205) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Missing scope parameter in authentication request
    at Promise.resolve.then (/data/web/blockchain.kmi.open.ac.uk/node/node_modules/@solid/oidc-rp/src/AuthenticationRequest.js:61:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[22/04/2020 02:15:32] [ERROR]  (node:14205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by jeff-zucker** [comment]
Upgrade to the latest solid-auth-cli and this error should go away.  If it doesn't, let me know.

**Comment by Leoudayan** [comment]
@jeff-zucker  Nope :( It doesnt work. I upgraded the solid-auth-cli and even re-installed solid file manager with the folder install and npm run build. But the problem still persists. 

> [22/04/2020 03:21:32] [ERROR]  (node:4203) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Missing scope parameter in authentication request
>     at Promise.resolve.then (/data/web/blockchain.kmi.open.ac.uk/node/node_modules/@solid/oidc-rp/src/AuthenticationRequest.js:61:9)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> [22/04/2020 03:21:32] [ERROR]  (node:4203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by jeff-zucker** [comment]
What OS are you on and what node version?  I can not reproduce the error in linux with the correct solid-auth-cli and @solid modules and @CxRes finds the same thing on Windows.

**Comment by Leoudayan** [comment]
@jeff-zucker  I actually installed it in a server (Linux I guess). But the client is on MacBook Pro. 

Npm version: 6.14.4.

**Comment by Leoudayan** [comment]
@jeff-zucker The thing is, I have another project that I completed 6 months ago and I just updated the npm packages and it still works. But when I try to set it up as a new project on a different server, I am facing this problem. You try to set it up as a new project (i.e) you have to install the solid-file-client and solid-auth-cli from scratch.

**Comment by Otto-AA** [comment]
What are you trying to accomplish? Setting up solid-filemanager on your server?

**Comment by Leoudayan** [comment]
@Otto-AA i am trying to just receive a string from client and create a file in solid POD. In my previous set up (which sits on a different server) it works. But when I want to do the same in a different server, it throwing this error. :(

**Comment by jeff-zucker** [comment]
@Leoudayan what version of solid-auth-cli is in the solid-file-client/node_modules/solid-auth-cli/package.json on the machine that fails?

**Comment by Leoudayan** [comment]
@jeff-zucker Please find the Json files below. 

> node/node_modules/solid-file-client/node_modules/solid-auth-cli/package.json
```

{
  "_from": "solid-auth-cli@^1.0.10",
  "_id": "solid-auth-cli@1.0.13",
  "_inBundle": false,
  "_integrity": "sha512-6DhBa+lvHgNuex2eB/nXcHxByG8jaW1WBxEc/RUm81SocunAoPOY0lsggnooYSf0XiLe+TsPqjltGAxSYC7SIw==",
  "_location": "/solid-auth-cli",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "solid-auth-cli@^1.0.10",
    "name": "solid-auth-cli",
    "escapedName": "solid-auth-cli",
    "rawSpec": "^1.0.10",
    "saveSpec": null,
    "fetchSpec": "^1.0.10"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/solid-auth-cli/-/solid-auth-cli-1.0.13.tgz",
  "_shasum": "4e2885441e9d6c1b1699c84210cdf0aae1154f9e",
  "_spec": "solid-auth-cli@^1.0.10",
  "_where": "/data/web/blockchain.kmi.open.ac.uk/node/node_modules/solid-file-client",
  "author": {
    "name": "Jeff Zucker"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@solid/cli": "0.1.3",
    "async": "^2.6.1",
    "cross-fetch": "^3.0.4",
    "jsonld": "^1.4.0",
    "n3": "^1.0.3",
    "solid-rest": "^1.1.7"
  },
  "deprecated": false,
  "description": "**a node/command-line Solid client with persistent login** <br> <br> [![NPM](https://nodei.co/npm/solid-auth-cli.png)](https://nodei.co/npm/solid-auth-cli/)",
  "devDependencies": {
    "rdflib": "^1.0.6"
  },
  "license": "MIT",
  "main": "src/index.js",
  "name": "solid-auth-cli",
  "scripts": {
    "test": "jest --coverage"
  },
  "version": "1.0.13"
}

```

> node/node_modules/solid-auth-cli/package.json 

```

{
  "_from": "solid-auth-cli",
  "_id": "solid-auth-cli@1.0.13",
  "_inBundle": false,
  "_integrity": "sha512-6DhBa+lvHgNuex2eB/nXcHxByG8jaW1WBxEc/RUm81SocunAoPOY0lsggnooYSf0XiLe+TsPqjltGAxSYC7SIw==",
  "_location": "/solid-auth-cli",
  "_phantomChildren": {
    "asynckit": "0.4.0",
    "aws-sign2": "0.7.0",
    "buffer-from": "1.1.1",
    "canonicalize": "1.0.1",
    "caseless": "0.12.0",
    "cross-fetch": "3.0.4",
    "delayed-stream": "1.0.0",
    "fast-json-stable-stringify": "2.0.0",
    "forever-agent": "0.6.1",
    "har-schema": "2.0.0",
    "http-signature": "1.2.0",
    "inherits": "2.0.3",
    "is-typedarray": "1.0.0",
    "isstream": "0.1.2",
    "json-stringify-safe": "5.0.1",
    "performance-now": "2.1.0",
    "psl": "1.8.0",
    "rdf-canonize": "1.1.0",
    "tunnel-agent": "0.6.0",
    "typedarray": "0.0.6",
    "universalify": "0.1.2",
    "uri-js": "4.2.2",
    "util-deprecate": "1.0.2",
    "xmldom": "0.1.19"
  },
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "solid-auth-cli",
    "name": "solid-auth-cli",
    "escapedName": "solid-auth-cli",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/solid-auth-cli/-/solid-auth-cli-1.0.13.tgz",
  "_shasum": "4e2885441e9d6c1b1699c84210cdf0aae1154f9e",
  "_spec": "solid-auth-cli",
  "_where": "/data/web/blockchain.kmi.open.ac.uk/node",
  "author": {
    "name": "Jeff Zucker"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@solid/cli": "0.1.3",
    "async": "^2.6.1",
    "cross-fetch": "^3.0.4",
    "jsonld": "^1.4.0",
    "n3": "^1.0.3",
    "solid-rest": "^1.1.7"
  },
  "deprecated": false,
  "description": "**a node/command-line Solid client with persistent login** <br> <br> [![NPM](https://nodei.co/npm/solid-auth-cli.png)](https://nodei.co/npm/solid-auth-cli/)",
  "devDependencies": {
    "rdflib": "^1.0.6"
  },
  "license": "MIT",
                        
```

**Comment by jeff-zucker** [comment]
@Leoudayan what that shows me is that you have the latest version of solid-auth-cli installed globally but the old version of solid-auth-cli installed within solid-file-client.  You should get the latest solid-file-client (1.0.5, just released right now) which should install the correct solid-auth-cli.

**Comment by Leoudayan** [comment]
@jeff-zucker I just updated it and it works :D :) Thanks a lot :) :)
