### ISSUE TITLE
Question: Can I fetch the foaf:name from the profile using this library?

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [jeff-zucker/solid-file-client#15]
Hi, thanks for providing this - It is really helpful.

I wanted to get the name of the logged in user to display in a file management app, and I've been trying to use the fetchAndParse method from my browser console to figure out the right way - with no luck.

I can see the returned object from fetchAndParse(<mywebid>) contains the name I want, but querying the graph is difficult as all the examples use rdflib (like your tests), but that doesn't appear to be available through SolidFileClient or SolidAuthClient.

Would I need to add rdflib to my project to be able to do this or is there some method already available to me?

I tried this, but it returned undefined:

```SolidFileClient.fetchAndParse("https://mistermagoo.inrupt.net/profile/card#me").then(g=>g.any("https://mistermagoo.inrupt.net/profile/card#me",'<http://xmlns.com/foaf/0.1/name>'))```

thanks

**Comment by jeff-zucker** [comment]
Yes, in a round-about way, the solid-file-client library gives you access to rdflib.js.  The thing returned by fetchAndParse() is an rdflib.js graph object, often referred to as kb.  So if you used rdflib.js directly you'd say something like var kb = $rdf.graph(), That is the object that gets returned by fetchAndParse() and you can use it the same as if you'd defined it directly. 
 For example, this code (which should run the same in or out of the browser) gets the foaf name from my profile without needing to invoke rdflib.js directly.  BTW, one problem with your code is that you are trying to use g.any() on literal URLs.  You can't do that in rdflib.js, you need to use the g.sym() to turn the literals into symbols as shown below

```javascript
const fc = SolidFileClient;
let url = "https://jeffz.solid.community/profile/card"
fc.fetchAndParse(url).then( kb => {
    var subj = kb.sym(url+"#me")
    var obj = kb.sym("http://xmlns.com/foaf/0.1/name")
    var names = kb.each(subj,obj)
    console.log(names[0].value)
}, err => console.log(err) );
```

**Comment by SQL-MisterMagoo** [comment]
Thank you so much, that is a big help!

**Comment by SQL-MisterMagoo** [comment]
@jeff-zucker Thanks very much - I got it working and started work on a Solid file browser in Blazor
https://twitter.com/mistermag00/status/1085356004349542400

**Comment by jeff-zucker** [comment]
Congrats! You should announce your app on the forum https://forum.solidproject.org/ and perhaps the glitter chat https://gitter.im/solid/app-development
