### ISSUE TITLE
Using iframe to login to a pod

### ISSUE THREAD

**Issue by neuronsupport** [jeff-zucker/solid-file-client#156]
Isnt it possible to use an iframe to login into a pod?

**Comment by bourgeoa** [comment]
I am not sure what you are looking for.

You could have a look to : https://github.com/bourgeoa/solid-file-widget/
demo link https://bourgeoa.solid.community/public/solid-file-widget/
This widget is used in https://github.com/bourgeoa/tiddlywiki-node-solid-server
demo https://bourgeoa.solid.community/public/tiddlywiki
