### ISSUE TITLE
sfc should refuse to delete POD root

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/solid-file-client#175]
move function has deleted the root of my POD 
https://github.com/solid/solidcommunity.net/issues/27

**Comment by bourgeoa** [comment]
@scenaristeur v1.2.2 should also close issue for deleteFolder() which is a recursive delete.
SFC do not correct simple delete() on root or rootAcl. This is a fetch delete the correction is left to NSS.
In practice it will fail with 409 unless you delete all contents before.
