### ISSUE TITLE
Uncaught TypeError: "exports" is read-only

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/solid-file-client#178]
Hi @jeff-zucker , using
```
 import auth from 'solid-auth-client';
import FC from 'solid-file-client'
const fc = new FC( auth )
```

i get this message : ```Uncaught TypeError: "exports" is read-only``` since update from 1.1.0 to 1.2.0, whereas sfc was ok before update

![image](https://user-images.githubusercontent.com/4020744/100561215-7b5d1080-32b8-11eb-8d3b-2bb0f86710f5.png)

**Comment by bourgeoa** [comment]
v1.2.2 should close issue
