### ISSUE TITLE
solidFile.checkSession() seems broken on error (version 0.4.6)

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#18]
`solidFile.checkSession().then( session => session.webId, err => ...)`

returns **`session.webId`** if Session exists, and **`Cannot read property 'webId' of null`** if Session not exist,
never return **`err`**

**Comment by jeff-zucker** [comment]
Thanks so much, sorry for all the bugs.  This one is fixed now in v0.4.7 now on npm.

**Comment by bourgeoa** [comment]
Sorry but it is not solved with 0.4.7, **same problem**
I checked my package.json and package-lock.json they have 0.4.7 version
