### ISSUE TITLE
Any examples implementing solid file client? 

### ISSUE THREAD

**Issue by Leoudayan** [jeff-zucker/solid-file-client#21]
it will be great if you could share any example projects which implements this solid-file-client

**Comment by jeff-zucker** [comment]
Well my own apps solid-ide and solid-shell both make use of solid-file-client.  And I believe, so does @scenaristeur's spoggy and @bourgeoa's tiddly-wki.  This file, part of the tests for solid-file-client gives examples of using all of the methods https://github.com/jeff-zucker/solid-file-client/blob/master/examples/common-base.js

**Comment by jeff-zucker** [comment]
Also, feel free to ask questions in the forum.  We're all learning here and no question is too simple.

**Comment by Otto-AA** [comment]
Could you provide an example of how to upload an arbitrary file? For instance .mp3 or .pdf?

I've tried it with an html input and the FileReader API, but didn't succeed that way. Somehow the file stored in the pod isn't recognized as mp3 by the browser (e.g. https://otman.solid.community/public/4.mp3).
```javascript
async function upload() {
    const file = input.files[0];
    const reader = new FileReader();
    
    reader.onload = (e) => {
      const fileData = e.target.result;
      const url = `${folderUrl}/${nameInput.value}`;
      console.log(await fileClient.updateFile(url, fileData));
    };
    reader.readAsText(file);
}
```

**Comment by jeff-zucker** [comment]
@Otto-AA - sorry, there is not yet any upload() method for the browser in solid-file-client.  You can upload from the command line with it, but not yet in a browser, you can also use the databrowser to upload with drag and drop onto the green plus.  I don't have time at the moment to troubleshoot the file-upload field, if you get it working, please contribute an example and I'll encorporate it into solid-file-client.  Otherwise, I'll try to get to it as soon as I can and let you know.

**Comment by Otto-AA** [comment]
I just found out (as mentioned [here](https://stackoverflow.com/a/40826943/6548154)), that the fetch API allows for taking a file as body parameter.
Here is a short example:
```javascript
const fileClient = SolidFileClient;
const fileInput = document.getElementById('file');

// Upload the currently selected file by the input element
const url = 'https://example.org/public/test/audio.mp3';
const content = fileInput.files[0];
fileClient.updateFile(url, content);
```

So I see no need to change that in the solid-file-client, maybe consider updating the documentation.
