### ISSUE TITLE
fetch errror TypeError: Failed to fetchhttps://bourgeoa/

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#23]
fetch errror TypeError: Failed to fetchhttps://bourgeoa/
in chrome debug 

> GET https://bourgeoa/ net::ERR_NAME_NOT_RESOLVED

in 

> async function authnFetch(storage, fetch, input, options) {

error line 

>  let resp = await fetch(input, options); // If the server then requests credentials, send them

`
`

**Comment by jeff-zucker** [comment]
Isn't that what we'd expect to see when DNS can't find https://bourgeoa?  And I think the errors are from solid-auth-client, not solid-file-client.  If I've misunderstood, let me know.
