### ISSUE TITLE
index.js:1128 GET https://www.bourgeoa.ga/.well-known/solid/logout 404

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#24]
> index.js:1128 GET https://www.bourgeoa.ga/.well-known/solid/logout 404

 problem arises systematically with logout() because https://www.bourgeoa.ga is not a solid Pod

to avoid Pb with Promise I need to 

> logout().then(  res => console.log(), err => console.log)

**Comment by jeff-zucker** [comment]
I need to find out more about what .well-known is supposed to be.  But I did find that it does not matter if the originating server is Solid or not.  Just create a folder ".well-known" in the root directory of your httpd and a folder "solid" inside that and an empty file "logout" inside that and the error message should go away.  The error originates in solid-auth-client.

**Comment by RubenVerborgh** [comment]
It's a hack to log out clients (until the OIDC implementation is complete). 404 is harmless (but we cannot hide it from the console; browsers won't let us).

**Comment by jeff-zucker** [comment]
Thanks for tracking this down.  I'll submit a PR to solid-auth-cli with a message indicating it's harmless.

**Comment by jeff-zucker** [comment]
Added more informative error message to solid-auth-client showing the GET failure is harmless.
