### ISSUE TITLE
Unable to retrieve folders from solid pod

### ISSUE THREAD

**Issue by Leoudayan** [jeff-zucker/solid-file-client#28]
Hi,

Me and my colleague used the solid-file-client with the older version of solid pod to write files to solid POD. I recently updated the solid version to Solid 5.0.0-beta.7. I am getting several errors when trying to list the pod contents using solid-file-client now.. Is there any major change with this update? Please help me with this.

**Comment by jeff-zucker** [comment]
5.0.0. made a change that requires *both* the app and the user to be authorized in the .acl files.  So no apps will work with 5.0.0. unless they are specifically authorized.  This means you need to edit one or more .acl files to include a reference to the *domain* of the app (not the actual address of the app.  So, using the standard data browser, edit  /public/.acl and add something like this:

**Comment by Leoudayan** [comment]
Hi Jeff,

Many thanks for your reply. Let me try this and get back to you.

**Comment by jeff-zucker** [comment]
I just got word that there is a 403 bug with the server which I'm told will be fixed this week.  So I would hold off on using 5.0.0 for the moment.

**Comment by Leoudayan** [comment]
Ah thanks! Right now i think i am updated to 5.0.0 beta 7. Is it possible for me to downgrade to v4.4.1? If so, would you tell me how exactly to do that? i am confused whether to use npm install solid 4.4.1 or replace the files in the server with the 4.4.1 source code.

**Comment by jeff-zucker** [comment]
Use npm to downgrade to an earlier version.  I forget the exact syntax but it's something like npm install -g ^4.0@nss ...  The npm docs should help.

**Comment by Leoudayan** [comment]
Hi Jeff, yes the syntax is npm install -g solid-server@3.4.1 

Thanks for this. Right now i am using your file client to browse the pod and insert files. I am not sure where the error is but it throws 500 server error. Will figure our tomorrow.
