### ISSUE TITLE
Maybe typo in remove function

### ISSUE THREAD

**Issue by Otto-AA** [jeff-zucker/solid-file-client#29]
Maybe this is intended, but I thought I mention it in case it is a typo:
In the remove function both, a successful and unsuccessful response, will be handled with `resolve`. Therefore errors of any nature wouldn't be detected here.

https://github.com/jeff-zucker/solid-file-client/blob/83df6e866447b3d0d3ead33362266b3a98e9cfbf/src/index.js#L186-L192

**Comment by jeff-zucker** [comment]
Thanks for catching this. My thinking is this: if remove() can't find the file in the first place, it should succeed - the goal of having the file not there is accomplished.  But other reasons for failure should be caught and reported so I need to put some logic into the err handling.

**Comment by jeff-zucker** [comment]
Fixed in version 1.0.0.
