### ISSUE TITLE
Set Accept:text/turtle when fetching a folder

### ISSUE THREAD

**Issue by Otto-AA** [jeff-zucker/solid-file-client#33]
As mentioned in [this issue](https://github.com/solid/node-solid-server/issues/1120), you will probably need to set the accept header to `Accept: text/turtle` when you try to fetch the root folder from a v5.0.0+ server.
I am not 100% sure if this is true, as I don't have the resources to try it out, but I think that's something which should be tested.

Here is a bit context from my solid-filemanager project: https://github.com/Otto-AA/solid-filemanager/issues/24
And this issue is probably related too: https://github.com/jeff-zucker/solid-file-client/issues/28

**Comment by kevinaquick** [comment]
where in the scheme of things does this setting change have to be made? i.e. is this solid server side or client side and where specifically if possible. Any help on this much appreciated as we have this issue at the moment.

**Comment by Otto-AA** [comment]
I think adding it to the fetch option of the readFolder function should be enough.
It is only necessary if the targeted pod is hosted on a server with v5.0.0 and only works if this server is updated with the master branch (and not the release bundle). See [here](https://github.com/solid/node-solid-server/issues/1120) for a bit more info.
https://github.com/jeff-zucker/solid-file-client/blob/f81edfd2d232cf2de1fe37e240efa5a831fc1cc8/src/index.js#L213
```javascript
fetch(url, { headers: { "Accept": "text/turtle" } }).then( folderRDF => { 
```

**Comment by jeff-zucker** [comment]
From my reading of https://github.com/solid/node-solid-server/issues/1120, I do not have a clear picture that this is a client issue or a server issue.  Noel's attempt to change the Accept header client-side was apparently *unsuccessful* so I don't see why I would change it in solid-file-client before we even know it fixes something which the client needs to fix.  An accept /* should also support accept text/turtle so I'm unclear why making the Accept more specific would help.  I haven't been able to find any reference to a need for the specific Accept header in the specs.  So, lacking a spec to go on and lacking an example that this fixes a problem, I'm going to hold off for now.  If I've missed something or my reasoning is off, please let me know, I'm by no means certain about this.

**Comment by kevinaquick** [comment]
Hi

I now have the solid-file-client working by making the change suggested effectively by Otto-AA . We are using the browser javascript file, and as there is only a minified version available in the current iteration I have edited the unminified older version of the browser solid_file_client.js file (if that makes sense to you). SO the change I have made is in the readFolder function as follows:

this.readFolder = async function(url){
	//url = url+"private/";
    var body = await self.fetch(url,  { headers: { "Accept": "text/turtle" }})
    //console.log(url);
   //console.log(body);
    if(!body) return false
    var graph = self.text2graph( body.value, url, "text/turtle" )
    if(!graph) return false
    return self.processFolder( graph, url, body.value ) 
}

With the addition of  { headers: { "Accept": "text/turtle" }} to the fetch statement the code now. works once again! Without this change I got a javascript parsing error returned I believe

Kevin

**Comment by jeff-zucker** [comment]
Ah, OK, thanks much.  I hadn't realized the change worked for anyone.  I'll
update solid-file-client.

**Comment by jeff-zucker** [comment]
I wonder how this relates to this statement in the [spec](https://github.com/solid/solid-spec/blob/master/api-rest.md) which seems to indicate that omitting the Accept header **is the same as** specifying text/turtle.

*IMPORTANT: a default Content-Type: text/turtle will be used for requests for RDF resources or views (containers) that do not have an Accept header*.

**Comment by Otto-AA** [comment]
I haven't looked into the spec so I can't speak from that perspective, but I'll try to clarify the issue a bit:
**Prior to v5.0.0**:
When fetching the root folder of a pod, a turtle file is returned, even if `Accept: */*` is set.
**Release version of v5.0.0**:
When fetching the root folder of a pod, a html file is returned if `Accept: */*` is set. Setting `Accept: text/turtle` will cause an internal server error due to a bug (500 - `Error translating between RDF formats`).
**Master branch of v5.0.0**:
When fetching the root folder of a pod, a html file is returned if `Accept: */*` is set. Setting `Accept: text/turtle` will return the wanted turtle file.

I don't know if that change is documented somewhere or even if it is intended, it's just the behavior I noticed and learned from the issue.

**Comment by jeff-zucker** [comment]
Thank you for that very clear statement of the issue, I understand it much better after reading your summary.  It seems to me that the pre-5.0.0 behavior is the correct one.  The server should send a Turtle representation of the Container.  A client or the dataBrowser is free to display the HTML page instead, but a client should get a folder-listing when they do  a GET on a folder.  This seems like a server issue to me.  Have you reported this as an issue on solid/node-solid-server?  I think that would be a good idea and you are best qualified to raise it.

**Comment by Otto-AA** [comment]
I get your point and also feel that the old behavior better suits the spec and is more intuitive to use. As I honestly haven't read much of the spec of solid, I don't know if the root folder is a special kind of container and therefore is treated differently. But for instance I've noticed, that I also can't simply create a new item in this container in 5.0.0 with my filemanager. So it doesn't _seem_ to serve exactly the same use case as before. But as I've already mentioned before, I don't know much of the spec. I will look into it when I find more time.

**Comment by jeff-zucker** [comment]
I don't recall anything in the spec differentiating the root folder from any other, but that doesn't stop implementors from differentiating as there's nothing in the spec that says it can't be different either.

**Comment by Otto-AA** [comment]
The issue has been fixed now. I would suggest to keep the Accept header for now, as some servers likely aren't updated to the patch and I don't see any disadvantage from setting it to `text/turtle`. If you think so too I would close this issue now.

**Comment by jeff-zucker** [comment]
Thanks @Otto-AA.  @bourgeoa added the accept flag.  I agree that it is harmless to leave it in.
