### ISSUE TITLE
separate rdflib and solid-auth-client from the bundle

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#34]
The current webpack configuration bundles rdflib and solid-auth-client in with solid-file-client.  It would be cleaner, I think, to not include them in the bundle.  The user would have to include them in script tags or requires, but that would give them control over the version.  I think the way this is done is with the webpack.config externals setting - it specifies things which are dependencies but are not bundled.

**Comment by bourgeoa** [comment]
It will temporarily break any app using the actual bundle as latest.  I understand why I only should use a versioned app.

**Comment by bourgeoa** [comment]
in `webpack.window.config.json`

```
 module.exports = {
 ///
    externals = {
    rdflib : 'rdflib',
    solid-auth-client : solid-auth-client'
    },
 ///
```

Do I keep **`solid-file-cli`** in the bundle or shall I export it also, or even delete it from the package.json dependencies.

I suppose I need to modify the browser and node examples with requires.

Are the tests accurate ?

Is there any reason to keep separate `webpack.common.config.js` and `webpack.window.config.json` separate except that it works.

**Comment by jeff-zucker** [comment]
The issue of breaking things for current users is part of why I haven't tackled this before.  I suppose we could make two bundles - leave the current one as-is and make a second one that doesn't include rdflib and solid-auth-client and document that.   I assume you mean "solid-auth-cli" rather than "solid-file-cli" (I am beginning to hate the similarity in names but oh well).  We definitely need to keep it as a dependency but we should set it to "null" in the webpack (look at how rdflib does this) so that it is not bundled.  My brain can't quite wrap itself around the question of whether we need two webpack configs.  We need to  end up I think with three versions 1) web-ready 2) nodejs using import 3) nodejs using require which is the src.  I'm not really sure how #2 happens - babel yes, not sure about webpack.  And I'm not sure why it is needed except it becomes the source of #1.

**Comment by jeff-zucker** [comment]
The tests are fairly minimal and require logins if I recall.  Eventually it would be great to have jest tests that did not require login (could be run against file:// URLs).  Jest is pretty simple, you can look at solid-rest-file to see how I did it.

**Comment by bourgeoa** [comment]
PR #44 makes rdflib and solid-auth-client as externals. The point is to have the <script> tags in the good order : 
- rdflib
- solid-auth-client
- solid-file-client

**Comment by jeff-zucker** [comment]
Great work on this @bourgeoa, thanks
