### ISSUE TITLE
0.4.9 do not pass tests : replace fullname by fullName

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#35]
`console.warn node_modules/solid-auth-client/lib/index.js:36
    window.SolidAuthClient has been deprecated.

  console.warn node_modules/solid-auth-client/lib/index.js:37
    Please use window.solid.auth instead.

 FAIL  tests/index.test.js (6.796s)
  ✓ Use readFile() to get data from a public profile (487ms)
  ✕ Use readFolder() to get data from a public folder (318ms)
  ✓ Use fetchAndParse() to get data from a public profile (251ms)

  ● Use readFolder() to get data from a public folder

    ReferenceError: fullname is not defined

      126 |   const fullName = url.replace(/\/$/, '');
      127 |   const name = fullName.replace(/.*\//, '');
    > 128 |   const parent = fullName.substr(0, fullname.lastIndexOf("/"))+"/";
          |                                     ^
      129 |   return {
      130 |     type: folderType,
      131 |     name,

      at Object.fullname [as processFolder] (lib/folderUtils.js:128:37)
      at processFolder (lib/index.js:217:41)
`

solution
> 128 |   const parent = fullName.substr(0, fullName.lastIndexOf("/"))+"/";

**Comment by jeff-zucker** [comment]
Yes, it's been a long time since I looked at the tests, sorry.
