### ISSUE TITLE
updateFile adds .ttl extension to the file

### ISSUE THREAD

**Issue by ZeeshanJan** [jeff-zucker/solid-file-client#39]
While updating a `.ttl` file (e.g., `myfile.ttl`) - the function `updateFile` also updates the file as `myfile.ttl.ttl` (and it goes on).

**Comment by jeff-zucker** [comment]
How are you calling updateFIle?  You should *either* pass a filename with an extension *or* pass a contentType but never both.  So updateFile("foo.ttl",newContent) and updateFile("foo",newContent,"text/turle") should both result in a file foo.ttl but updateFile("foo.ttl",newContent,"text/turtle") will result in foo.ttl.ttl ... If that's not the problem ,please show me the code you use to call it.

**Comment by ZeeshanJan** [comment]
Yes, I was updating the file with both parameters.
Thank you for the help.
