### ISSUE TITLE
v1.0.0 : Error Interface

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#48]
Sorry to be opening this can of worms @Otto-AA, but if there is ever a time to examine the essentials, it is now.  So, the more I think about it, the more I like the idea of always resolving, never requiring the user to use catch, always returning a response.ok Boolean, status and statusText.  I welcome being talked out of this if it's a bad idea.

Here are my reasons for wanting to switch away from throw/catch.  

1. If the user forgets to use catch, an error causes a big ugly "unhandled rejection" message that doesn't really make clear who forgot to handle it.

2. It's easy (for me at least) to typo when creating a catch, lots of symbols to type

3. If the user is is avoiding "await" for whatever reason, this kind of thing becomes really difficult with catch:
```javascript
  readFile.then( r=>{
    if(r.ok) do_X(r.body)
    else if(r.status==404) do_Y()
    else do_Z()
  })
```
4. anyone familiar with the fetch API already knows this way
@bourgeoa do you think this adds or removes complexity for the learning user?

**Comment by bourgeoa** [comment]
I'm sorry but I don't understand what add or remove complexity.

**Comment by jeff-zucker** [comment]
Currently we use catch like this:
```javascript
  let content = await readFile(url).catch(e=>{show_err(e)})
  if( content ) show(content)
``` 
I am thinking of this instead:
```javascript
  let response = await readFile(url)
  if( response.ok ) show(response.body)
  else show_err(response)
``` 
If we do it the first way, methods will resolve on success and reject on error and the user must catch the error.   In the new way, methods always resolve.  If they find an error, they put it in the response.status and response.statusText and set response.ok to false and resolve that.  Since they never reject, the user doesn't need to catch.  Does this make sense?  If not, please ask again.

**Comment by jeff-zucker** [comment]
The response.body would, in the easy methods, but not he API methods be already transformed so there would as we do now in solid-file-client so there is no need  for the user to do .text()

**Comment by bourgeoa** [comment]
I don't know if my question as any sense but does it as any consequence on promises resolved with Promise.all because it is allways resolved. Apart this what you propose is that for the learning user the fetch response is used in lieu of the usual catch error promise. I like the idea because I think promise added to me a level of complexity.

**Comment by jeff-zucker** [comment]
Promises would work the same.  These are still asynchronous.  The only difference is that the user will need to examine the response object rather than needing to catch the error.

**Comment by jeff-zucker** [comment]
I think I've found a best-of-both-worlds solution.  Here's my
current thinking on error interfaces:

By default, all methods will reject errors and the user should
use catch to trap them. This is the current behavior.

If, when the SolidFileClient instance is initialized, the user
passes a "responseInterface" flag, all errors will be stored in
a fetch API response object and will not be rejected. In that case,
the user, instead of catching errors, can check response.ok and
response.status.  I can	supply these response objects on top of
SolidApi,there is no need for SolidApi to do anything differently
in either interface.  I've tested this and it works with a very	light
layer.	I'll commit it tomorrow or Monday.

There will be no need to distinguish in the documention between "easy"
and "advanced" methods - they will all work the same - either all throw
errors or all sending response objects.  The only method that has both
an easy and advanced option is readFile/get because readFile() will parse
the body and get() will not.  The fetchAndParse	method is only in SolidFileClient.
Other than those two methods, all of the methods are used from SolidApi
either directly	(in the catch interface) or indirectly (in the response	
interface, which will do the catching for the user but nothing else).

**Comment by Otto-AA** [comment]
Yeah, I like your idea. So we are going to add an option parameter to the SolidFileClient constructor?

**Comment by jeff-zucker** [comment]
Yes, I've already added it.  I'll make it a hash rather than a single value so if we discover a need for other options later we're all set.

**Comment by Otto-AA** [comment]
I've changed the SolidApi.fetch method to throw if response.ok is false in https://github.com/jeff-zucker/solid-file-client/pull/50. I think if we have this option to switch between those two error handlings they should be consistent across all methods, that's why I changed that.

**Comment by jeff-zucker** [comment]
> I've changed the SolidApi.fetch method to throw

That makes total sense.  as long as you throw a response object, all is good.

**Comment by jeff-zucker** [comment]
Could I just say that I am very excited about how this is all coming together.  I really appreciate the thoughts and work you are both putting in and I think we're going to end up with something really usable and powerful.

I have started a [task-tracking document](https://github.com/jeff-zucker/solid-file-client/blob/otto-changes/higher-level-tasks.md) to keep track of all of the various issues, our progress on tests, tasks still to do.  I made one for the high-level methods, with an explanation of what I see as a high-level method and which methods those are.

**Comment by bourgeoa** [comment]
I have been through the filesystem and found that there can be .meta.acl files. There is a use case at '/'(root). I suppose it implies we have to look for :
.acl, .meta and .meta.acl in getLinks()

**Comment by jeff-zucker** [comment]
Is that in the spec?  In my mind, .meta is barely implemented.  It can't be used on files and it does nothing for folders.  I am not sure how much effort we should spend on these kind of edge cases of something which is likely to change drastically over time.  There is no documentation that I know about for when and how to use .meta files or how NSS treats them or how they should be treated in the spec so I'm not sure we should go out of our way to support something there is little other support for

**Comment by Otto-AA** [comment]
> Could I just say that I am very excited about how this is all coming together. I really appreciate the thoughts and work you are both putting in and I think we're going to end up with something really usable and powerful.

Yeah, I am also really excited about this update. I think it will make things easier for many developers who want to work with solid :)

**Comment by Otto-AA** [comment]
And as a side note in case it wasn't clear: I think the low level api methods (fetch, get, move, ...) should also have the same error behavior as the high level api. So if `throwErrors` is set to false they should also resolve with the response instead of throwing. I guess this will require many more of those wrappers, I will look if I find something to automatically wrap all api methods into this error handler.

**Comment by jeff-zucker** [comment]
Sure that makes sense, more work on the coding end, less on the documentation end.

**Comment by jeff-zucker** [comment]
And I need to do the same with login etc. - wrap them so the error in the two ways.

**Comment by Otto-AA** [comment]
What do you think about moving the error logic to a separate class/handler? If we do it one level above SolidFileClient, we could also just throw errors in SolidFileClient and don't need to check if we should throw or resolve the error.

And I've found a [Stackoverflow answer](https://stackoverflow.com/a/37771608/6548154) which shows how to iterate though class methods. This means it should be possible to automatically catch errors and either resolve or throw them. I think this would be good against code duplication and also we can't forget to add an error handler this way.

**Comment by jeff-zucker** [comment]
I can't quite picture how that would work, but if it's something you can easily implement, it sounds like a good idea.

**Comment by jeff-zucker** [comment]
I am thinking we also want a setInterface() method so users can switch between throwErrors and response whenever they want.  The location header thing is a good example - people may want to usually throw errors but when they need the location header for e.g. createFile, they can switch to response object for that one call.

**Comment by bourgeoa** [comment]
With recursiveDelete on one situation the error response was Object Response and not Array(Object Response)
The situation is deleteRecursively a folder `foo/` containing `foo/test.txt.acl` so should be `error 309`

It is depending on 1 parameter, the use of HTTP/2 that's why it does not occur : 
- on  solid.community
- it does appear on my server with chrome (HTTP/2) and not with my firefox ((HTTP1.1)

PR #82 should do it
It is included in https://www.bourgeoa.ga/solid-ide-test-v1

**Comment by Otto-AA** [comment]
I think it would be good to use custom Error class(es) for this project.

Advantages I see:
- We could provide a custom error message
- People who expect an Error instance won't be surprised with an Array or Response object
- We can provide additional data (e.g. successful and rejected API requests)
- We can easily check if it is a fetch Error or something we accidentally made wrong

For instance (based on a [MDN example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types)):
```javascript
class FetchError extends Error {
  constructor(response, ...params) {
    // Pass remaining arguments (including vendor specific ones) to parent constructor
    super(...params)

    this.name = 'SolidFetchError'
    if (!params.length)
      this.message = `${response.status} ${response.url}` // Default message

    // Custom debugging information
    this.response = response
  }
}

class ComposedFetchError extends Error {
  constructor({ successful, rejected }, ...params) {
    // Pass remaining arguments (including vendor specific ones) to parent constructor
    super(...params)

    this.name = 'ComposedFetchError'
    if (!params.length)
      this.message = rejected.map(res => `${res.status} ${res.url}`).join('\n') // Default message

    // Custom debugging information
    this.successful = successful
    this.rejected = rejected
  }
}

// Creating errors
throw new FetchError(response)
throw new ComposedFetchError({ successful: [res1, res2], rejected: [res3, res4, res5] })

// Catching
fileClient.delete(url)
  .catch(err => {
    if (err instanceof FetchError) {
      console.error(err)
    } else {
      // Not a fetch error. We somehow produced an Error another way
      console.error('Unexpected error')
      console.error(err)
    }
  })
```

If you think this is a good way to handle errors, I could implement it this way.

**Comment by bourgeoa** [comment]
I have no experience, just that I found a bit complex an array of response errors.
What do you think **to only have one class** with for composed functions : 

> err.result = { successful: [res1, res2], rejected: [res3, res4, res5] }

So we have the usual error structure, plus err.result.
`err.status` and `err.message` should contain specific err values when `err.result.rejected` exists.

**Comment by Otto-AA** [comment]
@bourgeoa I'm not sure if I understood you correctly, but I guess you mean something like this?
```javascript
class FetchError extends Error {
  constructor({ successful, rejected }, ...params) {
    // Pass remaining arguments (including vendor specific ones) to parent constructor
    super(...params)

    this.name = 'FetchError'
    if (!params.length)
      this.message = rejected.map(res => `${res.status} ${res.url}`).join('\n') // Default message

    // Custom debugging information
    this.result = { successful, rejected }
  }
}

// Creating new Errors
throw new FetchError({ successful: [res1, res2], rejected: [res3, res4, res5] })
throw new FetchError({ rejected: [res] }, 'Cannot delete non-empty container') 

// Handling Errors
fileClient.delete(url)
  .catch(err => {
    if (err instanceof FetchError) {
      console.error(err)
      console.error(err.result.rejected) // e.g. [ {status: 404, url: '...', ...}]
    } else {
      // Not a fetch error. We somehow produced an Error another way
      console.error('Unexpected error')
      console.error(err)
    }
  })
```

How would you set `err.status` if we have multiple rejected requests with different statuses? For instance if I try to use copyFolder and I get a "403" and "413" response?

I personally would prefer to use `err.responses.rejected` instead of `err.result.rejected` as it is more descriptive.

**Comment by bourgeoa** [comment]
- From my readings
https://stackoverflow.com/questions/27286857/can-i-use-http-response-424-when-a-request-requires-another-request-to-be-done-f
For `err.status` you may use 424 or if you don't like 409
- no name preference for new field
- `err.result.rejected` is an array of object. Can it be a JSON object that you can easily stringify ? It may be nonsense. Or array of array ?

**Comment by Otto-AA** [comment]
> From my readings
https://stackoverflow.com/questions/27286857/can-i-use-http-response-424-when-a-request-requires-another-request-to-be-done-f
For err.status you may use 424 or if you don't like 409

I think you misunderstood me here. The problem is, that only one `err.status` cannot properly represent many rejected requests. Using 424 or 409 wouldn't solve this problem, the user would still not know what the cause of the errors were. In particular if 409 was sent by the server or added by us.

This is the reason why I considered making two Error classes. One for single rejected requests (which then can have a status property) and one for multiple rejected requests (for which a status property doesn't make sense imo). 

> err.result.rejected is an array of object. Can it be a JSON object that you can easily stringify ? It may be nonsense. Or array of array ?

For what use case would you stringify it? In general you could call `JSON.stringify(err.responses.rejected)` and get a string like `"[{ status: 123, url: 'abc', ... }, { status: 234, url: 'cde' , ...}, , ...]"`.
If it is intended for humans to read something like this should work:
```javascript
err.responses.rejected.map(res => `${res.status} ${res.url}`).join('\n')
// outputs something like: "123 abc\n234 cde"
```

**Comment by bourgeoa** [comment]
That's why I thought `424` would tell something was wrong and check `err.response.rejected`
It can even be the `err.message`.
Yes I was thinking at human readable. This is easier for newbies. So it's perfect.
Don't take me bad I am not a coder, reading the code I only partially see the results. You make me learn

**Comment by jeff-zucker** [comment]
Version 1.0.0. is now released, closing  background issues.
