### ISSUE TITLE
module not found in angular

### ISSUE THREAD

**Issue by samapraku** [jeff-zucker/solid-file-client#6]
I am trying to use this library in an angular project. I initially installed it using "npm install solid-file-client" and then use " import fileclient from 'solid-file-client' "; and it worked.

However, after your latest update, I get module not found error when  import after installing.

Is there something I'm missing?

**Comment by linonetwo** [comment]
Is this on the npm? I can't find it, it's 404 https://www.npmjs.com/package/solid-file-client

**Comment by samapraku** [comment]
@linonetwo no it's not on npm. I added the entry below to package.json dependencies section
"solid-file-client": "jeff-zucker/solid-file-client"

After that, I run "npm install" or "npm install solid-file-client"

**Comment by jeff-zucker** [comment]
Please wait about an hour and try again.  I am in the middle of uploading a major revision and stopped in middle to sleep.  I will be putting it on npm in the next few minutes.  I'll message your when I'm done.

**Comment by jeff-zucker** [comment]
It won't be in the ./src directory, the module-import/esm version will be in dist/esm.  Ready soon.

**Comment by jeff-zucker** [comment]
@samapraku  Alright, it is on npm now so a normal "npm install" should work.  The build you want will be located in node_modules/solid-file-client/dist/esm/.  Please let me know if that works for you.

**Comment by samapraku** [comment]
@jeff-zucker yes I can confirm it is working now. 
Using "import * as fileclient from 'solid-file-client'" works.

Thanks a lot for creating this library!

**Comment by jeff-zucker** [comment]
Yay!  That's what I like to hear.  Let me know if you have any questions or suggestions.
