### ISSUE TITLE
loginPopup() leads to the wrong Origin being authorized

### ISSUE THREAD

**Issue by robmccoll** [jeff-zucker/solid-file-client#72]
Tested with:
- master @ 229a11e84ba86651e13221ce4927c3ea5d20947f
- https://solid.comunity/ @ v5.1
- Firefox 68.0.1, Chrome 76.0.3809.87

Steps to reproduce:
- Be sure to run these steps for a combination of pods and origins that have not previously had scopes for read / write / create / modify / delete granted between them.
- Enter proper credentials and configuration for a pod on the community solid server into `examples/browser-test.html` and `examples/solid-credentials.json`.
- Open `examples/browser-test.html` in the browser of your choice, note that the "Authorize <origin> to access your Pod?", screen is displayed, Authorize access, and see that the tests pass.
- Change credentials and configuration in `examples/browser-test.html` and `examples/solid-credentials.json` to a different user.
- Modify `examples/common-base.js` to use the `popupLogin()` method of the `SolidFileClient`.
- Reload `examples/browser-test.html`. Note that the login now produces a pop up window containing `https://solid.community/common/popup.html`. Select the Solid Community option and log in.
- The community server does not prompt to authorize the origin from which the tests are run since the redirect actually came from itself.
- The remaining tests will fail with `TypeError: r is null` because the response from attempting to create the basic container will be `403 Origin Unauthorized` with a `text/html` body similar to:
```
No permission to access this resource

You are currently logged in as https://robmccoll.solid.community/profile/card#me, but do not have permission to access https://robmccoll.solid.community/public/.
```

Suggested fix - I would think the popup page is going to need to be hosted from the origin using this library unless there is a way within Solid or the specific popup implementation to pass the origin through it.

I actually came across this from solid-ide. If I attempt to use it from any origin without going through a different login process to grant the authorizations first, all create / write / modify / delete operations fail.

**Comment by robmccoll** [comment]
Related https://github.com/solid/solid-auth-client/issues/130

**Comment by jeff-zucker** [comment]
This is a solid-auth-client issue.  Solid-File-Client no longer directly handles login.  But opening this in Solid-IDE since it may need to be changed there.
