### ISSUE TITLE
getFolderItems() produces invalid folder URI for non-https protocols

### ISSUE THREAD

**Issue by theWebalyst** [jeff-zucker/solid-file-client#77]
When adding a folder item that has a protocol other than `https` the resulting item's URI is not valid because the `//` after the protocol is replaced with a single `/`.

So: 
- `https://dweb/404/` correctly results in an item name '404' with a URI of `https://dweb/404/`
- `safe://dweb/404/` results in an item name '404', but with an invalid URI of `safe:/dweb/404/`

I haven't tested with an 'http' URI, but as far as I can see that,  'ipfs', 'dat' etc. would fail too.

I've have a fix for this so let me know if you would like a pull request.

Note:
As a rule it is best to avoid matching protocols explicitly unless you are looking just for the matched protocol because while most applications will work, some will not and protocols do evolve.

I've done a brief search for other instances of matching protocols in solid-file-client, but didn't find any, although there is a commented out version of the buggy function `getFolderItems()` (in both `lib/folderUtils.js` and `src/folderUtils.js`) that has this same issue, so maybe that should be removed.

**Comment by jeff-zucker** [comment]
We've moved on to a completely different code base at https://github.com/jeff-zucker/solid-file-client/tree/otto-changes.  But I'll check to see if this is still a problem.  Thanks!

**Comment by jeff-zucker** [comment]
I am pretty sure this is fixed in v.1.0.0. which is now on npm.  If not, please re-open.
