### ISSUE TITLE
createFile & getting prepended numerical ID 

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/solid-file-client#8]
Hi @jeff-zucker 
You say 
```
createFile(URL,contentType)

fileClient.createFile(newFile).then(success => {
  console.log(`Created file ${newFile}.`);
}, err => console.log(err) );

This method creates a new empty file. The contentType should be specified either in the URL's extension or in the contentType parameter, but not both.

NOTE : if the file already exists, the solid.community server (and others) will create an additional file with a prepended numerical ID 
```
Looks good and created some files https://holacratie.solid.community/public/Tension/ 
BUT, 
Is there a way to get the real name of file created with the "prepended numerical ID" ?
- i want to create a file https://holacratie.solid.community/public/Tension/testnom1.ttl
- but if it exists, it creates a https://holacratie.solid.community/public/Tension/c44cb150-testnom1.ttl
- could I get the real url of the created file with something like 
```
succes.created = "https://holacratie.solid.community/public/Tension/c44cb150-testnom1.ttl"
```
and  you could change doc to "   fileclient.createFile(newFile,contentType,**content**).then(success ..."

txs

**Comment by jeff-zucker** [comment]
Good idea.  In the meantime, try updateFile(), which removes previous versions if they exist, so you never get the prepended duplicates.

**Comment by scenaristeur** [comment]
I don't want to remove : the aim is multi users app.
One could want to create a file with a name  that could eventualy already exist (created by another user), I don't want to delete or update old files,  so the prepend ID is a good thing and the new file has another id but I'd like to retrieve that ID

**Comment by scenaristeur** [comment]
I was working with an old version (0.1.0) of solid-file-client, so with 0.1.0 the 'add' function can be changed, like this  
```
    var response = await solid.auth.fetch( parentFolder, request )
    .catch(err=>{self.err=err;return false})
    if(response.ok)
    {    //  console.log("location", response.headers.get('location'))
     // console.log(parentFolder)
      var location = response.headers.get('location')
      file = location.substr(location.lastIndexOf('/') + 1)
      return parentFolder+file;
      //return true
    }
```
instead of true 
perharps could you do he same with the last version , thx

**Comment by jeff-zucker** [comment]
I think that will just return the original name, not the name of the newly created duplicate.  I believe the info should be in the headers, I'm checking.  BTW, there were big API changes after v.0.1.0 so hopefully you've switched to the newer versions.  I've just discovered how to override rdflib's fetch which means that lots of new rdflib goodies will be coming to solid-file-client.  For example, now it's got a recursive copyFolder() which copies a whole web tree, but I can swap a version using rdflib which has even more capabilities.  Thanks again for your help!

**Comment by jeff-zucker** [comment]
Oh dang, I just actually read your patch rather than skimming it. You already got it out of the headers. Thanks, I'll patch it now.

**Comment by jeff-zucker** [comment]
Your patch works like  a charm.

**Comment by scenaristeur** [comment]
your change looks nearly good, I can retrieve Prepend ID,  but it sounds that it add an extension ".ttl" where there is already one : 
this code

```
...
  console.log("url",this.url)
  var fields = this.fields
  console.log("TEST if file exist -> create or update");
  var nom = "unknown"
  for (var i = 0; i < fields.length; i++){
    if (fields[i].name == "Nom"){
      nom = fields[i].value.split(' ').join('_');
    }
  }
  var newFile = this.url+'/'+nom+".ttl";
  console.log(newFile)

  var content = this.createContent(this.url, this.fields)

  var contentType = 'text/turtle';
  this.fileclient = SolidFileClient;
  var realfile = this.fileclient.createFile(newFile,content,contentType).then(created => {
    console.log(created)
    app.success = created;
    console.log(`Created file ${created}`);
  },
  err => console.log(err) )
```

GIVES me a created file *https://holacratie.solid.community/public/Tension/testnom1.ttl.ttl* with 2*'.ttl'

1st test to create a https://holacratie.solid.community/public/Tension/testnom1.ttl file

```
url https://holacratie.solid.community/public/Tension 
TEST if file exist -> create or update 
https://holacratie.solid.community/public/Tension/testnom1.ttl 
https://holacratie.solid.community/public/

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix hol: <https://holacratie.solid.community/public/holacratie/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
<> rdfs:label "testnom1". 
<> hol:nom _:_-1146004873 . 
_:_-1146004873 rdfs:label "testnom1" . 
_:_-1146004873 rdf:type hol:Nom.  

XHRPOSThttps://holacratie.solid.community/public/Tension/
[HTTP/1.1 200 Connection established 150ms]
https://holacratie.solid.community/public/Tension/testnom1**.ttl.ttl** 
Created file https://holacratie.solid.community/public/Tension/testnom1**.ttl.ttl**

```
2nd TEST on the same file
```

url https://holacratie.solid.community/public/Tension
TEST if file exist -> create or update 
https://holacratie.solid.community/public/Tension/testnom1.ttl 
https://holacratie.solid.community/public/ 

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix hol: <https://holacratie.solid.community/public/holacratie/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
<> rdfs:label "testnom1". 
<> hol:nom _:_-1146004873 . 
_:_-1146004873 rdfs:label "testnom1" . 
_:_-1146004873 rdf:type hol:Nom.  

XHRPOSThttps://holacratie.solid.community/public/Tension/
[HTTP/1.1 200 Connection established 132ms]
https://holacratie.solid.community/public/Tension/03279990-testnom1**.ttl.ttl** 
Created file https://holacratie.solid.community/public/Tension/03279990-testnom1**.ttl.ttl** 
```
