### ISSUE TITLE
v1.0.0 readFolder

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#98]
taken from @jeff-zucker comments : 
> > Apologies if I'm rehashing things you've already discussed, here are my current thoughts:
>>
>>    readFolder()
>>
>>If we always return all files including *.meta and *.acl, we need to open each and every file to find their location. Could be a lot of overhead for large folders. Should we do that or should the user just invoke getLinks() themselves if they want to know those?

I open a new discussion because I already raised the question but don't find my comments anymore.

My thinking was the following : 

Actually readFolder returns a folder object containing among other properties :   
  - contentType,
  - folders : an array of folders
  - files and a array of files including if withAcl .meta and .acl

That could be heavy

My proposal would be to not include acl files, but to add a property : 
  - `links` : containing an object/array of the absolute/relative links to .acl (meta ?) taken from Head (without check for use) getItemLinks()
  - .meta could be added to files property after checking existence or create a property of its own
  - advantage : 
     . one access already existing to HEAD for contentType and links, no new access for copyFile(), copyFolder()
     . copyFolder() will add from the new property `links` the .meta to files as actually
     . copyFile() will do the check for existence of the `links` acl

What do you think ?

**Comment by Otto-AA** [comment]
In general, I think the user should have the possibility to make as few requests as necessary while getting what's desired.

For readFolder, I think there are four different levels what the user could want:
1. minimal version is making one request for the names of the files inside. 
2. more request-heavy option is to make one+n requests for the folder and all files inside it to also get the links (acl and meta) and possibly other metadata for them.
3. a recursive method to get a directory tree
4. a recursive method to get a directory tree with links and other metadata

I don't think that we have to implement 3 and 4 yet*, but I think it would be useful to have 1 and 2 ready before v1.0.0.

My proposal is to make two different methods for this: readFolder and readFolderWithLinks. If you prefer to separate it via options, we can also make a "withLinks" flag.

For returning this data, I would suggest to add the links to the resource they belong to. FolderData has an array of files and folders and each of these files/folders can have a "links.acl" and "links.meta" property.

Inspired by @bourgeoa comment, I could also imagine to use a .details property which also contains links, contentType, and the response itself. Then we could call the method readFolderDetails or smth like that.

**Comment by bourgeoa** [comment]
Is your proposal to have existing or expected links ? I was thinking to have expected not checking if they exists.

**Comment by Otto-AA** [comment]
We could have three methods, one without links, one with possible links and one with existing links. But I meant only the first two, also checking if they exist would be really many requests and likely not necessary in most cases (I guess).

**Comment by jeff-zucker** [comment]
I do not see any use for something that lists only where the linked files
would be if they existed.  When would someone use that information rather
than getting a listing of the linked files that actually exist?  I vote
that the default version lists only what we can get from reading the
Container once.  A "withLinks=true" could return all linked files that
actually exist.

**Comment by bourgeoa** [comment]
So OK we keep as it is
I close the issue

**Comment by Otto-AA** [comment]
> I do not see any use for something that lists only where the linked files
would be if they existed.  When would someone use that information rather
than getting a listing of the linked files that actually exist?

It could be used to reduce the amount of requests for retrieving all acl files, for instance to copy them. Here is a short comparison of a version which checks for existence and one which only list possible locations.

Version using all existing files:
1 GET request for folder (by the method)
n HEAD requests for each file in the folder getting links (by the method)
n HEAD requests for each acl file in the folder checking if they exist (by the method)
m GET requests for each existing file (by the user of the method, e.g. copyFolder)
= 1 + 2n + m requests, where n=(number of files in folder) and m=(number of existing acl files)

Version using all possible files:
1 GET request for folder (by the method)
n HEAD requests for each file in the folder getting links (by the method)
n GET requests for each possible acl file (by the user, e.g. copyFolder. 404 responses can be filtered here)
= 1 + 2n requests

If we also include .meta files the difference is even bigger.

I don't think that this will be used often by users of solid-file-client, but at least internally for copyFolder it seems useful. Externally only if our users are keen to make few requests, but then it could prove useful. Also it wouldn't be much more effort, as these functions build up well on each other (readFolder < readFolderWithPossibleLocations < readFolderWithLinks).

**Comment by jeff-zucker** [comment]
Yes, I see that it has internal uses.  I have a hard time seeing a user use
for it though.  If you think there might be, then I'm fine with leaving it
as an option, so there would be three calls:

  readFolder( url )  // returns the folder & what it directly contains
  readFolder( url, { withLinks : true  } ) // returns folder, its contents,
all existing .meta and .acl of folder and of contents
  readFolder( url, withPossibleLinks : true } ) // same as above but all
possible, links existing or not
